### ISSUE TITLE
Target of URI doesn't exist: 'package:carrier_info/carrier_info.dart'.

### ISSUE THREAD

**Issue by Jayvd** [Zfinix/carrier_info#10]
I have added  `carrier_info: ^2.0.0` in my pubspec.yam yet, there is an error saying `Target of URI doesn't exist: 'package:carrier_info/carrier_info.dart'. `whenever I am importing this package..

Any thoughts??

**Comment by ivirtex** [comment]
Run "flutter clean" in your folder, reinstall Flutter extension in your IDE. This problem is not related to this library.
