### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by vtthinh** [Zfinix/carrier_info#3]
Running "flutter pub get" in flutter_carrier_info...            
The current Dart SDK version is 2.12.0-141.0.dev.
Because flutter_carrier_info requires SDK version >=2.12.0 <3.0.0, version solving failed.
pub get failed (1; Because flutter_carrier_info requires SDK version >=2.12.0 <3.0.0, version solving failed.)
Process finished with exit code 1

**Comment by vtthinh** [comment]
Hello, anyone using this packet? Please give me the solution!

**Comment by Zfinix** [comment]
Hiya i have updated the plugin to null saftey
