### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by kostadin24** [Zfinix/carrier_info#8]
Launching lib\main.dart on Mi Note 3 in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\carrier_info-2.0.0\android\src\main\kotlin\com\chizi\carrier_info\MethodCallHandlerImpl.kt: (112, 35): Unresolved reference: radioType
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\carrier_info-2.0.0\android\src\main\kotlin\com\chizi\carrier_info\MethodCallHandlerImpl.kt: (137, 44): Unresolved reference: radioType

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':carrier_info:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by Jayvd** [comment]
I have this problem too, any idea how to solve it? @kostadin24

**Comment by Zfinix** [comment]
> Simply update the library version to fix this problem

Thank you so much Jayvd
